package:
  name: restraintlib
  version: 2019.11.1

source:
  git_url: https://github.com/mkowiel/restraintlib.git

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python
    - setuptools
    - pytest
  host:
    - pip
    - python
  run:
    - python
    - cctbx >=2020.8
    - scikit-learn ==0.20.3
    - pandas ==0.24.2
    - six

test:
  imports:
    - restraintlib

about:
  home: https://github.com/mkowiel/restraintlib
  license: BSD
