package:
  name: restraintlib
  version: 2019.11.1

source:
  git_url: https://github.com/mkowiel/restraintlib.git

requirements:
  build:
    - python
    - pytest
  run:
    - python
    - cctbx
    - scikit-learn
    - pandas
    - six

test:
  imports:
    - restraintlib

about:
  home: https://github.com/mkowiel/restraintlib
  license: BSD
