package:
  name: restraintlib
  version: 2021.07.1

source:
  git_url: https://github.com/mkowiel/restraintlib.git

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python
    - setuptools
    - pytest
  host:
    - pip
    - python
  run:
    - python
    - cctbx >=2020.8
    - scikit-learn ==0.20.3
    - pandas ==0.24.2
    - six

test:
  imports:
    - restraintlib
  requires:
    - pytest
  source_files:
    - tests/*.py
    - tests/*.cif
    - tests/*.pdb
  commands:
    - pytest


about:
  home: https://github.com/mkowiel/restraintlib
  license: BSD
